movies/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('contact/', include('contact.urls')),

    path('pages/', include('django.contrib.flatpages.urls')),

    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('movieapp.urls')),

]

urlpatterns += i18n_patterns(
    path('accounts/', include('allauth.urls')),
    path('', include('movieapp.urls')),
    # path('contact/', include('contact.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),

    # path('logout/', auth_views.LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieapp/models.py
from django.db import models
from datetime import date

from django.urls import reverse

# Create your models here.

class Category(models.Model):
    """Категория"""
    name = models.CharField(verbose_name="Имя категории", max_length=255)
    # Подключить текстовый редактор
    description = models.TextField(verbose_name="Описание", blank=True)
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Actor(models.Model):
    """Актеры и режиссеры"""
    name = models.CharField(verbose_name="Имя", max_length=255)
    age = models.PositiveIntegerField(verbose_name="Возраст", default=0)
    # Подключить текстовый редактор
    description = models.TextField(verbose_name="Описание", blank=True)
    image = models.ImageField(verbose_name="Изображение", upload_to="actors/")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('actor_detail', kwargs={"pk": self.id})

    class Meta:
        verbose_name = "Актеры и режиссеры"
        verbose_name_plural = "Актеры и режиссеры"


class Genre(models.Model):
    """Жанры"""
    name = models.CharField(verbose_name="Имя жанра", max_length=255)
    description = models.TextField(verbose_name="Описание", blank=True)
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"


class Movie(models.Model):
    name = models.CharField(verbose_name="Название", max_length=255)
    tagline = models.CharField(verbose_name="Слоган", max_length=255, blank=True)
    description = models.TextField(verbose_name="Описание", blank=True)
    poster = models.ImageField(verbose_name="Постер", upload_to="movies/")
    year = models.PositiveSmallIntegerField(verbose_name="Год выхода", default=2019, null=True)
    country = models.CharField(verbose_name="Страна", blank=True, max_length=100)
    directors = models.ManyToManyField(Actor, verbose_name="Режиссер", related_name="movie_director")
    actors = models.ManyToManyField(Actor, verbose_name="Актеры", related_name="movie_actors")
    genres = models.ManyToManyField(Genre, verbose_name="Жанры")
    world_priemere = models.DateField("Премьера в мире", default=date.today)
    budget = models.PositiveIntegerField("Бюджет", help_text="Указывать в долларах")
    fees_world = models.PositiveIntegerField("Сборы в мире", default=0, help_text="Указывать в долларах")
    category = models.ForeignKey(Category, verbose_name="Категория", on_delete=models.SET_NULL, null=True)
    url = models.SlugField(max_length=160, unique=True)
    draft = models.BooleanField("Черновик", default=False)

    def __str__(self):
        return self.name

    def get_review(self):
        return self.reviews.filter(parent__isnull=True)

    def get_absolute_url(self):
        return reverse("movie_detail", kwargs={"slug": self.id})

    class Meta:
        verbose_name = "Фильм"
        verbose_name_plural = "Фильмы"


class MovieShots(models.Model):
    """Кадры из фильма"""
    title = models.CharField("Заголовок", max_length=100)
    description = models.TextField(verbose_name="Описание", blank=True)
    shots = models.ImageField("Изображение", upload_to="movie_shots/")
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="фильм", related_name="shots", default=1)


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Кадр"
        verbose_name_plural = "Кадры"


class RatingStar(models.Model):
    """Звезда рейтинга"""
    value = models.SmallIntegerField("Значение", default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"
        ordering = ["-value"]


class Rating(models.Model):
    """Рейтинг"""
    ip = models.CharField("IP адрес", max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name="звезда")
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="фильм", related_name="rating")

    def __str__(self):
        return f"{self.star} - {self.movie}"

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"

class Reviews(models.Model):
    """Отзывы"""
    email = models.EmailField()
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Сообщение", max_length=5000)
    parent = models.ForeignKey(
        "self", verbose_name="Родитель", on_delete=models.SET_NULL, blank=True, null=True
    )
    movie = models.ForeignKey(Movie, verbose_name="Фильм", on_delete=models.CASCADE, related_name='reviews')

    def __str__(self):
        return f"{self.name} - {self.movie}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

templates/include/content_actor_detail.html
<div class="left-ads-display col-lg-8">
    <div class="row">
        <div class="desc1-left col-md-5">
            <p style="text-align: center"><img src="{{ object.image.url }}" class="img-fluid" alt=""></p>
        </div>
        <div class="desc1-right col-md-7 pl-lg-4">
            <h3 class="editContent" style="outline: none; cursor: inherit;">
                {{ object.name }}</h3>

            <ul>
                <li style="list-style: none"><span><b>Возраст:</b> {{ object.age }}</span></li>
                {% if movie_director %}
                    <li style="list-style: none"><span><b>Режиссер:</b>
                        {% for movie in object.movie_director.all %}
                            <a href="{{ movie.get_absolute_url }}">{{ movie.name }} </a>
                        {% endfor %}
                    </span>
                    </li>
                {% endif %}
                {% if object.movie_actors %}
                <li style="list-style: none"><span><b>Актер:</b>
                    {% for movie in object.movie_actors.all %}
                        <a href="{{ movie.get_absolute_url }}">{{ movie.name }} </a>
                    {% endfor %}
                </span>
                </li>
                {% endif %}
                <div class="share-desc">
                    <div class="share">
                        <h4 class="editContent"
                            style="outline: none; cursor: inherit;">
                            Share:</h4>
                        <ul class="w3layouts_social_list list-unstyled">
                            <li>
                                <a href="#" class="w3pvt_facebook editContent"
                                   style="outline: none; cursor: inherit;">
                                                <span class="fa fa-facebook-f"
                                                      style="outline: none; cursor: inherit;"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_twitter editContent"
                                   style="outline: none; cursor: inherit;">
                                                <span class="fa fa-twitter"
                                                      style="outline: none; cursor: inherit;"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_dribble editContent"
                                   style="outline: none; cursor: inherit;">
                                                <span class="fa fa-dribbble"
                                                      style="outline: none; cursor: inherit;"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div>
        </div>
    </div>
    <div class="row sub-para-w3layouts mt-5">

        <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
            Биография: {{ object.name }}</h3>

        <p class="editContent" style="outline: none; cursor: inherit;">
            {{ object.description|safe }}
        </p>


    </div>
    <hr>
{#    <div class="row">#}
{#        <div class="single-form-left">#}
{#            <!-- contact form grid -->#}
{#            <div class="contact-single">#}
{#                <h3 class="editContent" style="outline: none; cursor: inherit;">#}
{#                                    <span class="sub-tittle editContent"#}
{#                                          style="outline: none; cursor: inherit;">02</span>Оставить отзыв</h3>#}
{##}
{#                <form action="{% url 'add_review' movie.id %}" method="post" class="mt-4" id="formReview">#}
{#                    {% csrf_token %}#}
{#                    <div class="form-group editContent"#}
{#                         style="outline: none; cursor: inherit;">#}
{#                        <input type="hidden" name="parent" id="contactparent" value="">#}
{#                        <label for="contactcomment" class="editContent"#}
{#                               style="outline: none; cursor: inherit;">Ваш комментарий *#}
{#                        </label>#}
{#                        <textarea class="form-control border" rows="5"#}
{#                                  id="contactcomment" required="" name="text"></textarea>#}
{#                    </div>#}
{#                    <div class="d-sm-flex">#}
{#                        <div class="col-sm-6 form-group p-0 editContent"#}
{#                             style="outline: none; cursor: inherit;">#}
{#                            <label for="contactusername" class="editContent"#}
{#                                   style="outline: none; cursor: inherit;">Имя *#}
{#                            </label>#}
{#                            <input type="text" class="form-control border"#}
{#                                   id="contactusername" required="" name="name">#}
{#                        </div>#}
{#                        <div class="col-sm-6 form-group ml-sm-3 editContent"#}
{#                             style="outline: none; cursor: inherit;">#}
{#                            <label for="contactemail" class="editContent"#}
{#                                   style="outline: none; cursor: inherit;">Email *#}
{#                            </label>#}
{#                            <input type="email" class="form-control border"#}
{#                                   id="contactemail" required="" name="email">#}
{#                        </div>#}
{#                    </div>#}
{#                    <button type="submit"#}
{#                            class="mt-3 btn btn-success btn-block py-3"#}
{#                            style="outline: none; cursor: inherit;">Отправить#}
{#                    </button>#}
{#                </form>#}
{#            </div>#}
{#            <!--  //contact form grid ends here -->#}
{#        </div>#}
{#    {% for review in object.get_review %}#}
{#        <div class="media py-5">#}
{##}
{#                <img src="/static/bundles/images/te2.jpg" class="mr-3 img-fluid" alt="image"#}
{#                     style="outline: none; cursor: inherit;">#}
{#                <div class="media-body mt-4">#}
{#                <h5 class="mt-0 editContent"#}
{#                    style="outline: none; cursor: inherit;">{{ review.name }}</h5>#}
{#                <p class="mt-2 editContent" style="outline: none; cursor: inherit;">#}
{#                    {{ review.text }}#}
{#                </p>#}
{#                <a href="#formReview" onclick="addReview('{{ review.name }}, ','{{ review.id }}')">Отправить</a>#}
{#                {% for rev in review.reviews_set.all %}#}
{#                    <div class="media mt-5 editContent" style="outline: none; cursor: inherit;">#}
{#                        <a class="pr-3" href="#">#}
{#                            <img src="/static/bundles/images/te1.jpg" class="img-fluid " alt="image"#}
{#                                 style="outline: none; cursor: inherit;">#}
{#                        </a>#}
{#                        <div class="media-body">#}
{#                            <h5 class="mt-0 editContent">{{ rev.name }}</h5>#}
{#                            <p class="mt-2 editContent">{{ rev.text }}</p>#}
{#                            <div><a href="#formReview"#}
{#                                    onclick="addReview('{{ rev.name }}, ','{{ rev.id }}')">Отправить</a></div>#}
{#                        </div>#}
{##}
{#                    </div>#}
{#                {% endfor %}#}
{#            </div>#}
{#        </div>#}
{#    {% endfor %}#}
{#    </div>#}
</div>

templates/include/content_common.html
<div class="left-ads-display col-lg-9">
                        <div class="row">
                            {% for movie in movie_list %}
                            <div class="col-md-4 product-men">
                                <div class="product-shoe-info editContent text-center mt-lg-4" >
                                    <div class="men-thumb-item">
                                        <a href="{{ movie.get_absolute_url }}">
                                        <img src="{{ movie.poster.url }}" class="img-fluid" alt="" >
                                        </a>
                                    </div>
                                    <div class="item-info-product">
                                        <h4 class="">
                                            <a href="{{ movie.get_absolute_url }}" class="editContent" >{{ movie.name }}</a>
                                        </h4>

                                        <div class="product_price">
                                            <div class="grid-price">
                                                <span class="money editContent" >{{ movie.tagline }}</span>
                                            </div>
                                        </div>
                                        <ul class="stars">
                                            <li><a href="#"><span class="fa fa-star" aria-hidden="true" ></span></a></li>
                                            <li><a href="#"><span class="fa fa-star" aria-hidden="true" ></span></a></li>
                                            <li><a href="#"><span class="fa fa-star-half-o" aria-hidden="true" ></span></a></li>
                                            <li><a href="#"><span class="fa fa-star-half-o" aria-hidden="true" ></span></a></li>
                                            <li><a href="#"><span class="fa fa-star-o" aria-hidden="true" ></span></a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <!--<div class="grid-img-right mt-4 text-right bg bg1" >
                            <span class="money editContent" >Flat 50% Off</span>
                            <a href="moviesingle.html" class="btn" >Now</a>
                        </div>-->
                    </div>

templates/include/content_single.html
{% load static i18n %}
<div class="left-ads-display col-lg-8">
    <div class="row">
        <div class="desc1-left col-md-5">
            <p style="text-align: center"><img src="{{ object.poster.url }}" class="img-fluid" alt=""></p>
        </div>
        <div class="desc1-right col-md-7 pl-lg-4">
            <h3 class="editContent" style="outline: none; cursor: inherit;">
                {{ object.name }}</h3>

            <ul>
                <li style="list-style: none"><span><b>{% trans 'Год' %}:</b> {{ object.year }}</span></li>
                <li style="list-style: none"><span><b>{% trans 'Страна' %}:</b> {{ object.country }}</span>
                </li>
                <li style="list-style: none"><span><b>{% trans 'Слоган' %}:</b> {{ object.tagline }}</span>
                </li>
                <li style="list-style: none">
                                    <span><b>{% trans 'Режиссер' %}:</b>
                                        {% for director in object.directors.all %}
                                            {% if director == object.directors.all.last %}
                                                <a href="{{ director.get_absolute_url }}">{{ director }}</a>
                                            {% else %}
                                                <a href="{{ director.get_absolute_url }}">{{ director }}</a>,
                                            {% endif %}
                                        {% endfor %}
                                    </span></li>
                <li style="list-style: none"><span><b>{% trans 'Актеры' %}:</b>
                    {% for actor in object.actors.all %}
                        {% if actor == object.actors.all.last %}
                            <a href="{{ actor.get_absolute_url }}">{{ actor }}</a>
                        {% else %}
                            <a href="{{ actor.get_absolute_url }}">{{ actor }}</a>,
                        {% endif %}
                    {% endfor %}
                                </span></li>
                <li style="list-style: none"><span><b>{% trans 'Жанр' %}:</b>
                    {% for genre in object.genres.all %}
                        {% if genre == object.genres.all.last %}
                            {{ genre }}
                        {% else %}
                            {{ genre }},
                        {% endif %}
                    {% endfor %}
                                </span>
                </li>
                <li style="list-style: none"><span><b>Премьера в мире:</b> {{ object.world_priemere }}</span>
                </li>
                <li style="list-style: none">
                    <span><b>Бюджет:</b> ${{ object.budget }}</span></li>
                <li style="list-style: none"><span><b>Сборы в мире:</b> ${{ object.fees_world }}</span>
                </li>

                <li style="list-style: none">
                    <form action="{% url 'add_rating' %}" method="post" name="rating">
                        <b>Рейтинг:</b>
                        {% csrf_token %}
                        <input type="hidden" value="{{ object.id }}" name="movie">
                         <span class="rating">
                        {% for k, v in star_form.fields.star.choices %}

                            <input type="radio" id="rating{{ v }}" name="star" value="{{ k }}">
                            <label for="rating{{ v }}">{{ k }}</label>

                        {% endfor %}
                            </span>
                    </form>

                </li>

                <div class="share-desc">
                    <div class="share">
                        <h4 class="editContent"
                            style="outline: none; cursor: inherit;">
                            Share:</h4>
                        <ul class="w3layouts_social_list list-unstyled">
                            <li>
                                <a href="#" class="w3pvt_facebook editContent"
                                   style="outline: none; cursor: inherit;">
                                                <span class="fa fa-facebook-f"
                                                      style="outline: none; cursor: inherit;"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_twitter editContent"
                                   style="outline: none; cursor: inherit;">
                                                <span class="fa fa-twitter"
                                                      style="outline: none; cursor: inherit;"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_dribble editContent"
                                   style="outline: none; cursor: inherit;">
                                                <span class="fa fa-dribbble"
                                                      style="outline: none; cursor: inherit;"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div>
        </div>
    </div>
    <div class="row sub-para-w3layouts mt-5">

        <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
            О фильме {{ object.name }}</h3>
        <p>
            {% for shot in object.shots.all %}
                <img src=" {{ shot.shots.url }}" class="img-fluid" alt="" style="width: 200px;">
            {% endfor %}
        </p>
        <p class="editContent" style="outline: none; cursor: inherit;">
            {{ object.description|safe }}
        </p>


    </div>
    <hr>
    <div class="row">
        <div class="single-form-left">
            <!-- contact form grid -->
            <div class="contact-single">
                <h3 class="editContent" style="outline: none; cursor: inherit;">
                                    <span class="sub-tittle editContent"
                                          style="outline: none; cursor: inherit;">02</span>Оставить отзыв</h3>

                <form action="{% url 'add_review' movie.id %}" method="post" class="mt-4" id="formReview">
                    {% csrf_token %}
                    <div class="form-group editContent"
                         style="outline: none; cursor: inherit;">
                        <input type="hidden" name="parent" id="contactparent" value="">
                        <input type="hidden" name="path" id="path" value="" >
                        <label for="contactcomment" class="editContent"
                               style="outline: none; cursor: inherit;">Ваш комментарий *
                        </label>
{#                        <textarea class="form-control border" rows="5"#}
{#                                  id="contactcomment" required="" name="text"></textarea>#}
                        {{ form.text }}
                    </div>
                    <div class="d-sm-flex">
                        <div class="col-sm-6 form-group p-0 editContent"
                             style="outline: none; cursor: inherit;">
                            <label for="contactusername" class="editContent"
                                   style="outline: none; cursor: inherit;">Имя *
                            </label>
{#                            <input type="text" class="form-control border"#}
{#                                   id="contactusername" required="" name="name">#}
                            {{ form.name }}
                        </div>
                        <div class="col-sm-6 form-group ml-sm-3 editContent"
                             style="outline: none; cursor: inherit;">
                            <label for="contactemail" class="editContent"
                                   style="outline: none; cursor: inherit;">Email *
                            </label>
{#                            <input type="email" class="form-control border"#}
{#                                   id="contactemail" required="" name="email">#}
                            {{ form.email }}
                        </div>
                        {{ form.captcha }}
                    </div>
                    <button type="submit"
                            class="mt-3 btn btn-success btn-block py-3"
                            style="outline: none; cursor: inherit;" onclick="addUrl()">Отправить
                    </button>
                </form>
            </div>
            <!--  //contact form grid ends here -->
        </div>
    {% for review in object.get_review %}
        <div class="media py-5">

                <img src="/static/bundles/images/te2.jpg" class="mr-3 img-fluid" alt="image"
                     style="outline: none; cursor: inherit;">
                <div class="media-body mt-4">
                <h5 class="mt-0 editContent"
                    style="outline: none; cursor: inherit;">{{ review.name }}</h5>
                <p class="mt-2 editContent" style="outline: none; cursor: inherit;">
                    {{ review.text }}
                </p>
                <a href="#formReview" onclick="addReview('{{ review.name }}, ','{{ review.id }}')">Отправить</a>
                {% for rev in review.reviews_set.all %}
                    <div class="media mt-5 editContent" style="outline: none; cursor: inherit;">
                        <a class="pr-3" href="#">
                            <img src="/static/bundles/images/te1.jpg" class="img-fluid " alt="image"
                                 style="outline: none; cursor: inherit;">
                        </a>
                        <div class="media-body">
                            <h5 class="mt-0 editContent">{{ rev.name }}</h5>
                            <p class="mt-2 editContent">{{ rev.text }}</p>
                            <div><a href="#formReview"
                                    onclick="addReview('{{ rev.name }}, ','{{ rev.id }}')">Отправить</a></div>
                        </div>

                    </div>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
    </div>
</div>
<script>
    {#function addUrl(){#}
    {#    let $path = document.querySelector('#path');#}
    {#    let url = document.URL;#}
    {#    $path.value = url;#}


    function addReview(name, parentId) {
        let $textarea = document.querySelector('#contactcomment');
        let $contactparent = document.querySelector('#contactparent');
        $textarea.value = name;
        $contactparent.value = parentId;
    }

    const rating = document.querySelector('form[name=rating]')
    rating.addEventListener('change', function (){
        let data = new FormData(this);
        fetch(`${this.action}`,{
            method: 'POST',
            body: data
        })
        .then(response => alert('Рейтинг установлен'))
        .catch(error => alert('Ошибка'))
    })
</script>

templates/include/left_sidebar_latest_movies.html
{% load movie_tags %}


<div class="deal-leftmk left-side">

    <h3 class="sear-head editContent">Последние добавленные</h3>
    {% get_latest_movies as latest_movie %}
    {% for movie in latest_movie %}
    <div class="special-sec1 row mt-3 editContent">
        <div class="img-deals col-md-4">
            <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
        </div>
        <div class="img-deal1 col-md-4">

            <a href="{{ movie.get_absolute_url }}" class="editContent">
                <h3 class="editContent">{{ movie.name }}</h3>
            </a>
        </div>
    </div>
    {% endfor %}
</div>

templates/include/pagination.html
<ul class="pagination">
    {% if page_obj.has_previous %}
        {% if page_obj.number|add:'-3' > 1 %}
            <li class="pagination__item">
                <a href="?{{ q }}{{ genre }}{{ year }}page=1">1</a>
            </li>
        {% endif %}
        {% if page_obj.number|add:'-3' >= 3 %}
            <li class="pagination__item pagination__item--dots">
                    <a href="?{{ q }}{{ genre }}{{ year }}page={{ page_obj.previous_page_number|add:'-3' }}">
                <span class="pagination__link">• • •</span>
                </a>
            </li>
        {% endif %}
    {% endif %}
    {% if paginator.page_range|length > 1 %}
        {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="pagination__item active">
                    <a class="pagination__link" href="#">{{ i }}</a>
                </li>
            {% elif i > page_obj.number|add:'-4' and i < page_obj.number|add:'4' %}
                <li class="pagination__item">
                        <a class="pagination__link" href="?{{ q }}{{ genre }}{{ year }}page={{ i }}">{{ i }}</a>
                </li>
            {% endif %}
        {% endfor %}
    {% endif %}
    {% if page_obj.has_next %}
        {% if page_obj.number|add:'4' < page_obj.paginator.num_pages %}
            <li class="pagination__item pagination__item--dots">
                    <a href="?{{ q }}{{ genre }}{{ year }}page={{ page_obj.next_page_number|add:'3' }}">
                <span class="pagination__link">• • •</span>
                </a>
            </li>
        {% endif %}
        {% if page_obj.number|add:'3' < page_obj.paginator.num_pages %}
            <li class="pagination__item">
                    <a class="pagination__link" href="?{{ q }}{{ genre }}{{ year }}page={{ page_obj.paginator.num_pages }}">
                        {{ page_obj.paginator.num_pages }}
                    </a>
            </li>
        {% endif %}
    {% endif %}
</ul>